#!/usr/bin/env ruby

file = ARGV[0] || File.dirname(__FILE__) + '/../data/All.cmd'
new_file = file.gsub(File.extname(file), ".sco")

File.open(new_file, 'w') do |out|
  File.open(file, 'r').each_line do |line|
    size, op_code, *data = line.strip.split(',')
    if (1 + Array(data).size) == size.to_i
      case op_code.to_i
        when 12
          out.puts data.map { |d| [d.to_i >> 4, d.to_i & 0x0F] }.flatten.join
        else
          puts op_code
      end
    end

  end
end
